name: Update Repos on Push to Main

on:
  push:
    branches:
      - main

jobs:
  execute_and_update:
    runs-on: ubuntu-24.04

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Execute the Python script
    - name: Execute Python script
      run: python3.11 syntaxRegexGenerator.py

    # Update the first repository
    - name: Push updated file to vscode-syntax-highlighter
      env:
        REPO_TOKEN: ${{ secrets.PUSH_TOKEN }}
      run: |
        git clone https://$REPO_TOKEN@github.com/Xenon-Lang-Org/vscode-syntax-highlighter.git
        cp -f xenon.tmLanguage.json vscode-syntax-highlighter/syntaxes/xenon.tmLanguage.json
        cd vscode-syntax-highlighter
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add syntaxes/xenon.tmLanguage.json
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -m "Update generated file"
          git push origin main
        fi

    # Update the second repository
    - name: Push updated file to docs
      run: |
        git clone https://$REPO_TOKEN@github.com/Xenon-Lang-Org/docs.git
        cd docs
        sed -i '/\/\/ -- XENON LANG -- \/\/.*/,$d' theme/highlight.js
        echo -e "// -- XENON LANG -- //" >> theme/highlight.js
        cat ../xenonHighlighter.js >> theme/highlight.js
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add theme/highlight.js
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -m "Update target file"
          git push origin main
        fi
